name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Generate package-lock.json if missing
        run: |
          if [ ! -f package-lock.json ]; then npm install --package-lock-only; fi
      - name: Install dependencies (npm ci)
        run: npm ci
      - name: Build
        run: npm run build